data:
  block_size: 512
  cnhubertsoft_gate: 10
  duration: 2
  encoder: contentvec768l12
  encoder_ckpt: pretrain/contentvec/checkpoint_best_legacy_500.pt
  encoder_hop_size: 320
  encoder_out_channels: 768
  encoder_sample_rate: 16000
  extensions:
  - wav
  f0_extractor: crepe
  f0_max: 800
  f0_min: 65
  sampling_rate: 44100
  train_path: data/train
  units_forced_mode: nearest
  valid_path: data/val
  volume_noise: 0
device: cuda
env:
  expdir: exp/diffusion-test
  gpu_id: 0
infer:
  method: dpm-solver
  speedup: 10
model:
  block_out_channels:
  - 256
  - 384
  - 512
  - 512
  n_chans: 512
  n_heads: 8
  n_hidden: 256
  n_layers: 2
  n_spk: 1
  type: Diffusion
  use_pitch_aug: true
train:
  amp_dtype: fp32
  batch_size: 48
  cache_all_data: true
  cache_device: cpu
  cache_fp16: true
  decay_step: 100000
  epochs: 100000
  gamma: 0.5
  interval_force_save: 10000
  interval_log: 10
  interval_val: 2000
  lr: 0.0002
  num_workers: 2
  save_opt: false
  weight_decay: 0
vocoder:
  ckpt: pretrain/nsf_hifigan/model
  type: nsf-hifigan
